### ISSUE TITLE
install

### ISSUE THREAD

**Issue by ghost** [smitmartijn/discord-table-builder#1]
how do i install without composer ?
i think i have installed it, but with errors.
running  your example i get `( ! ) Parse error: syntax error, unexpected 'throw' (T_THROW) in /usr/www/users/plplat/homebrew/discord/server-info-feed/discord-table-builder-main/src/DiscordEmbedTable.php on line 34`

ok, fixed now. i took out the Exception catch.

**Comment by smitmartijn** [comment]
You can just use the source, if you don't want to use composer (but I don't see why you wouldn't).

And it sounds like you're using a pretty old PHP version, this is built for PHP 8+
